### ISSUE TITLE
Group member is removed from the group on update

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#115]
1. Create a new User Store.
2. Add group1 in the `System User Store`.
3. Select just created store  and open new wizard for  group2 .
4. specify the group1 in Memebers(group2-wizard), Save the group2 and close the wizard.

![image](https://user-images.githubusercontent.com/3728712/44342335-4df74a80-a493-11e8-9dd0-b9ef47d7db18.png)

5. Go to wizard with  `system/group1` and add new Role- Administrator, save the system group.
6. Go to the grid and click on the non system group

Expected: system group should be in `Members`
Actual:

![image](https://user-images.githubusercontent.com/3728712/45688156-4d68d700-bb59-11e8-82bd-b0dc25dc6d23.png)

**Comment by ashklianko** [comment]
That looks a bit different on latest master:
![image](https://user-images.githubusercontent.com/4255706/45496217-9eee1c00-b77d-11e8-9b88-edcbeccab9df.png)

Now there's Roles and Groups section that shows group's **membershib**: group is a member of group **_gr2_** and has role.

This seems correct to me, @alansemenov ?
