### ISSUE TITLE
Users app - Permission report - System admin users

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-users#123]
* Explanation
  * Admin users (with the role 'system.admin') should have all nodes with all permissions

* Todo
  * In the permission report, make a special case if the user has the 'system.admin' role
    * No need to filter (All the nodes are visible for this user)
    * No need to check the permissions (This user will have all the permissions)

**Comment by ashklianko** [comment]
Also commited https://github.com/enonic/app-users/issues/121 here
