### ISSUE TITLE
ConfirmationDialog - wrong behavior for "Enter"-key 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#129]
1. Select a Role. press `Delete`
2. Confirmation dialog appears

Press "Enter" key
**Expected**: role should be removed, wizard closed
**Actual**:
roleis deleted but new wizard is opened

![image](https://user-images.githubusercontent.com/3728712/45221955-be87cf00-b2bb-11e8-9743-a343152a83a6.png)

**Comment by alansemenov** [comment]
Most likely the same problem as [here](https://github.com/enonic/app-contentstudio/issues/408)

**Comment by ashklianko** [comment]
Same for **ALL** dialogs with cancel button(delete, sort,move, publish, issue, etc.). To reproduce:
-open dialog
-use TAB key to switch focus to Cancel button
-press Enter on keyboard

Result - dialog is closed and edit dialog is open in background.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #818](https://github.com/enonic/lib-admin-ui/issues/818) via [**ZenHub**](https://www.zenhub.com/)
