### ISSUE TITLE
Aggregation types are displayed incorrectly for sorted list

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#136]
1. Open Filter Panel (Users)
2. Type 'Everyone'  in the search input
3. Select  Roles, then Users, then Stores checkboxes

![image](https://user-images.githubusercontent.com/3728712/45429949-f2dd0000-b6ac-11e8-9a91-e04e686dfdaa.png)

4. Uncheck `Roles` checkbox

Bug:
All checkboxes is getting not visible. Actually - there is a role with Everyone name, but grid is empty....

![image](https://user-images.githubusercontent.com/3728712/45430145-62eb8600-b6ad-11e8-8d59-2e9ca75d7866.png)

**Comment by alansemenov** [comment]
The list of types should always be filtered according to current search criteria (like in Content Studio's filter panel).
