### ISSUE TITLE
Permission Report - incorrect filtration of options in the repository selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#139]
1. Select an user in  grid and type `cms-repo` in ItemStatistic Panel, repo-options-filter

Bug: `system-repo`  should not be present in options, when  `cms-repo` has been typed

![image](https://user-images.githubusercontent.com/3728712/45495316-b3311980-b77b-11e8-870c-1c2dc45cc028.png)

**Comment by ashklianko** [comment]
Hyphen `-` is treated as a special char in elastic and is replaced with white space, thus **_"cms-repo"_** is same as **_"cms repo"_**; Query is **nGram** with **OR** operator, so rather **cms** or **repo** is enough to be contained in resulting match. 
@alansemenov , any further actions required for this?

**Comment by alansemenov** [comment]
No, that's correct behaviour.
