### ISSUE TITLE
Permissions report list - broken layout, when browser window's  width less than1024 x 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#140]
1. Select an user and generate several reports

Bug: 
![image](https://user-images.githubusercontent.com/3728712/45538572-1a001280-b810-11e8-8619-1850fc391d77.png)

**Comment by alansemenov** [comment]
I suggest on low resolutions replacing text on the button with an icon and breaking the report line in two, so that the two links are on the second line under repo name.
