### ISSUE TITLE
Not possible to change the "path" of the user

### ISSUE THREAD

**Issue by poi33** [enonic/app-users#1484]
![image](https://user-images.githubusercontent.com/3340349/223425004-a136ac61-057c-46e2-8dfc-8d84b5eb3c59.png)

The "/test" is not possible to change and save. 

After saving it gets disabled and can not be changed. 
Refreshing makes it editable again, but the old value shows again.

**Comment by rymsha** [comment]
Changing identity of a user (which is stored in a path) is not possible in XP. Path modification should be disabled in the app.

**Comment by rymsha** [comment]
duplicate of #1315, actually
