### ISSUE TITLE
BodyMask remains on grid, when 'NewPrincipalDialog' was escaped

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#170]
1. Open Users app, click on `New`
2. Press the `Enter` key
3. Press the `Escape` key

Bug:  `BodyMask` remains on **grid**

![image](https://user-images.githubusercontent.com/3728712/47793057-71a9fd00-dd2e-11e8-9cf6-1c5ba5e2a133.png)

Press the `Enter` key, then select `User`, wizard is opened and BodyMask is above the wizard

![image](https://user-images.githubusercontent.com/3728712/47793031-5d660000-dd2e-11e8-8951-9ad73988a869.png)

**Comment by alansemenov** [comment]
This should be a general fix for all modal dialogs - whenever the dialog is closed (no matter how) the mask should be removed.

**Comment by ashklianko** [comment]
It seems that in that case mask is really removed - one for each opened modal dialog :) The thing here is that NewPrincipalDialog doesn't get focus after opening, focus remains on a 'new' button and each time enter key is pressed you open one more dialog with one more mask behind.
