### ISSUE TITLE
Don't store user report file in the repo

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-users#181]
When generating user report, we create a new repository just to store the report file. We should instead push the generated file to the client once it's generated, avoiding storing it in the repo (and creating the repo in the first place). We don't need to show the line with generated repo details either, it should disappear once the report is generated and the file is pushed to the client.

![image](https://user-images.githubusercontent.com/11612490/49583971-0caf7b80-f95a-11e8-95d8-e296fec1b6dc.png)

This [PR/task](https://github.com/enonic/app-users/pull/145) can then be closed.

Contact @GlennRicaud for assistance if needed.

**Comment by GlennRicaud** [comment]
Keep in mind timeouts.
If you are sure that it will always finish before it times out, then why not.
