### ISSUE TITLE
Unhandled exception when creating an ID Provider with a name already in use

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#189]
1. Create a store with name "test", close the wizard
2. Open new store-wizard and tape "test" in name input
3. Click on Save button

Bug: Endless spinner is present on the wizard page and  impossible to close the tab 

![image](https://user-images.githubusercontent.com/3728712/51107743-c70b8b80-1800-11e9-881c-5518de588518.png)

**Comment by alansemenov** [comment]
We should give an error message, like we do in 6.15, but with a different text:

"ID Provider "_``<name>``_" could not be created. This name is already in use."

![image](https://user-images.githubusercontent.com/11612490/51827175-09e15f00-22e9-11e9-9514-eb7684f8544f.png)
