### ISSUE TITLE
App Users - Cannot delete a property set in an ID Provider config

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-users#241]
Again another problem with ID Provider config edition in App Users.
First guess is that it is linked to last issue https://github.com/enonic/app-users/issues/234

The display keeps blinking and in the end the property set is not removed

![Screenshot 2019-07-03 at 12 21 35](https://user-images.githubusercontent.com/12030113/60584435-880cca80-9d8d-11e9-8d79-47c390cb0b81.png)

**Comment by alansemenov** [comment]
Fixed in another issue
