### ISSUE TITLE
Keyboard Shortcuts stop working after closing 'New principal' dialog by pressing Esc key. 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#252]
1. Navigate to users, press `Ctrl+alt+n`
2. Press `Esc` key and close the dialog.
3. Press any Keyboard Shortcut in browse panel: 
 - `Ctrl+alt+n`
 - select a role then press `f4` or `ctrl+del`

4. Select a role in the grid and press `Arrow-down ` or `Arrow -Up` - this Key binding  stop working as well
BUG-   Keyboard Shortcuts do not work.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1179](https://github.com/enonic/lib-admin-ui/issues/1179) via [**ZenHub**](https://www.zenhub.com/)
