### ISSUE TITLE
Users app - Missing messages

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-users#28]
Messages are missing in CONFIG.messages like action.save
![screen shot 2017-08-03 at 10 01 15](https://user-images.githubusercontent.com/12030113/28912031-c6765e58-7832-11e7-8513-f4d4fb637a3d.png)

**Comment by GlennRicaud** [comment]
@srs: Some update about this problem
https://enonic.slack.com/archives/C1GAHTD0V/p1500555708473737

**Comment by srs** [comment]
It is fixed now.
