### ISSUE TITLE
ID provider wizard - Delete button does not get enabled after saving of new provider.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#281]
1. Click on New, select 'Id Provider'
2. Type a name and click on Save.

BUG: Delete button is disabled
Expected: `Delete` button should be enabled, because there are no users and groups  in this provider:  (Delete button is enabled in grid after selecting this provider)

 
![image](https://user-images.githubusercontent.com/3728712/70994496-6f943080-20df-11ea-947e-56558ca87a94.png)

**Comment by alansemenov** [comment]
Regression bug caused by the fix of https://github.com/enonic/app-users/issues/275. If Id provider is empty then Delete action should be enabled after save.
