### ISSUE TITLE
 Deleted group remains in grid after deleting filtered groups in wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#383]
1. Add 2 groups.
2. Select these groups and click on Show Selection: 

![image](https://user-images.githubusercontent.com/3728712/88049296-9034d500-cb5d-11ea-9b44-e2bdf626ce6b.png)

3. Click on Edit button , 2 wizards are opened - OK.
4. Click on `Delete` button in the first wizard then click on `Delete` in the second wizard.

BUG: One deleted group remains in grid. Error after clicking on the group 

![image](https://user-images.githubusercontent.com/3728712/88049216-6d0a2580-cb5d-11ea-9cbb-1289ebdbdc20.png)

**Comment by alansemenov** [comment]
@ashklianko Probably solved by refactoring?

**Comment by sgauruseu** [comment]
This bug is not reproducing now.
