### ISSUE TITLE
Error in console after adding new item in collapsed Groups/Roles/Users folder

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#446]
1. Groups folder is empty, add a new group.
2. Add the second group in collapsed Groups folder
BUG: Error appears in the console after saving the group

![image](https://user-images.githubusercontent.com/3728712/97870932-c2d99680-1d24-11eb-91b5-b20a9c3c19f1.png)

This issue does not reproduce when Groups folder is expanded
![image](https://user-images.githubusercontent.com/3728712/97870821-8dcd4400-1d24-11eb-8135-da4743951105.png)

**Comment by ashklianko** [comment]
Solved in https://github.com/enonic/app-users/pull/449
