### ISSUE TITLE
Delete button remains enabled after adding a user in ID provider

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#461]
see the similar issue that is fixed: https://github.com/enonic/app-users/issues/275

1. Add new provider.
2. Click on the provider and open wizard for new user.
3. Save new user and close the wizard.

BUG: Delete button in grid tollbar  is enabled after adding the user.
Expected - Delete button should be disabled
![image](https://user-images.githubusercontent.com/3728712/100871339-2fc18700-34b1-11eb-9b6f-7ce5b636f995.png)

**Comment by ashklianko** [comment]
Closely related to https://github.com/enonic/lib-admin-ui/issues/1627

**Comment by ashklianko** [comment]
Done in https://github.com/enonic/lib-admin-ui/pull/1681
