### ISSUE TITLE
Confirmation dialog about unsaved changes appears after saving and closing a provider with configurator

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#531]
Install `Auth ID Provider` app
1. Open wizard for new Provider, fill in all required inputs in the configurator 
![image](https://user-images.githubusercontent.com/3728712/108084031-cc44ff80-7084-11eb-8fd9-f5135bfd4144.png)

2. Click on `Save` button.
3. Click on `Close` icon.
4. 
**BUG**:  Confirmation dialog about unsaved changes appears

![image](https://user-images.githubusercontent.com/3728712/108083968-b9cac600-7084-11eb-9e1d-e1784239a982.png)

**Comment by ashklianko** [comment]
According to @sgauruseu issue is not reproduced anymore
