### ISSUE TITLE
Confirmation dialog about unsaved changes appears when a group is member of another group

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#538]
1. Create 2 groups.
2. Select `group 2` in members of the first group 

![image](https://user-images.githubusercontent.com/3728712/108686062-f58ee100-7505-11eb-9aa7-c0c695adf602.png)

3. Open `group 2`. 
4. Click on Close icon and try to close  `group 2` wizard

**BUG**:   Confirmation dialog about unsaved changes appears, when trying to close this group with role.

![image](https://user-images.githubusercontent.com/3728712/108686462-836acc00-7506-11eb-9ae1-d78406de912c.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-users/pull/597
