### ISSUE TITLE
Two different idproviders cant have the same email address 

### ISSUE THREAD

**Issue by poi33** [enonic/app-users#652]
If the system user store has an email in use a newly created userstore can not have a user with the same email.

**Comment by rymsha** [comment]
I'm slightly confused with this description
Is it a bug, or is it a feature request?

Most of the code I see requires idProviderKey to be specified together with email. If not provided, system id provider is used.
So, if it is a bug how do you reproduce it?

**Comment by sigdestad** [comment]
It's a bug for sure.
If you log into admin, install simple IDprovider you will not be able to create a user with the same e-mail as a user that already exists in system idp. There should not be any such checks across IDP's.

**Comment by rymsha** [comment]
Still not sure if it is a GUI bug, or core.

**Comment by rymsha** [comment]
This is apparently a feature https://github.com/enonic/xp/issues/6039

**Comment by sigdestad** [comment]
The mistanke here is obiously that someone forgot to write "per idprovider" in the task description. One are only supposed to use the same login (username) and email once, per idProvider.

**Comment by rymsha** [comment]
`principals/emailAvailable` endpoint did not receive idProvider value and looked for emails only in system-id-provider. This is somehow fixed in 7.8 where endpoint is moved to app-users application itself.
