### ISSUE TITLE
No edit icon and invalid layout for application in the ID provider wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#658]
1. Open wizard for new ID Provider, 
2. Select `Auth0 ID Provider` in applications selector .

BUG  - edit icon is not displayed in selected application, broken layout in the selected option

![image](https://user-images.githubusercontent.com/3728712/127301293-8c1a05d0-0b65-4e32-9981-b01aa1394273.png)

**Comment by alansemenov** [comment]
Standard ID Provider is a bad example, because it's not supposed to have the config/edit icon. But yes, other providers don't have it either.
