### ISSUE TITLE
"Select all" checkbox won't change alignment on mobile resolution

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-users#90]
![image](https://user-images.githubusercontent.com/11612490/42367659-3a54263a-8105-11e8-9a8e-e43ce2992305.png)

Works fine in Content Studio.

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #688](https://github.com/enonic/lib-admin-ui/issues/688) via [**ZenHub**](https://www.zenhub.com/)
